# this is where your migration files will live. it will be relative to your config file
migration_dir: i18n/migrate

# this is where your locale files will live (en.yml, es.yml, etc). it will be relative to your config file
locales_dir: config/locales

# choose either google_spreadsheets or crowd_translate as a backend
backend: google_spreadsheets

# number of threads to concurrently perform migration operations for locales (optional)
# concurrency: 4

# number of threads to concurrently perform push operation for locales (optional)
# push_concurrency: 4

# seconds to wait time between push operations per thread, can be used to avoid API throttling (optional)
# wait_seconds: 0

# this is the locale you will be translating from
main_locale: en

# put all other locales you want to use here, if they don't already exist, add them with i18n-migrations new-locale es
other_locales:
  - es

# you need a service account key in order to access google spreadsheets. This is the path to it, relative to your config file
google_service_account_key_path: i18n/google_drive_key.json

# each locale will have a spreadsheet that translators will use to do their work, these are the links to them
google_spreadsheets:
  es: https://docs.google.com/spreadsheets/d/YOUR_SPREADSHEET_ID/edit

# this is your api key to use google translate
google_translate_api_key: [INSERT_GOOGLE_TRANSLATE_API_KEY]

# put things like your product name here along with any possible mistranslations
do_not_translate:
  "I18n Migrations":
    - I18n Migraciones
