version: 2.1
orbs:
  ruby: circleci/ruby@2.0.0
jobs:
  rspec:
    docker:
      - image: cimg/ruby:3.1.3
    steps:
      - checkout
      - ruby/install-deps:
          pre-install-steps:
            -  run: bundle config build.nokogiri --use-system-libraries
      - ruby/rspec-test
      - store_test_results:
          path: spec/reports
workflows:
  test_suite:
    jobs:
      - rspec
