version: 2.1
orbs:
  ruby: circleci/ruby@1.8
jobs:
  rspec:
    docker:
      - image: cimg/ruby:3.1.2
    steps:
      - checkout
      - ruby/install-deps:
          bundler-version: 2.3.22
      - ruby/rspec-test
      - store_test_results:
          path: ~/rspec
workflows:
  test_suite:
    jobs:
      - rspec
