version: 2.1
orbs:
  ruby: circleci/ruby@2.0.0
jobs:
  rspec:
    docker:
      - image: cimg/ruby:2.7.7
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rspec-test
      - store_test_results:
          path: spec/reports
workflows:
  test_suite:
    jobs:
      - rspec
